-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-27 12:12:09 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE badania (
    id_badania NUMBER(6) NOT NULL,
    nazwa      VARCHAR2(100 BYTE),
    opis       CLOB
);

CREATE UNIQUE INDEX badania_pk ON
    badania (
        id_badania
    ASC );

ALTER TABLE badania ADD CONSTRAINT badania_pk PRIMARY KEY ( id_badania );

CREATE TABLE diagnozy (
    id_diagnozy NUMBER(6) NOT NULL,
    nazwa       VARCHAR2(100 BYTE),
    opis        CLOB
);

CREATE UNIQUE INDEX diagnozy_pk ON
    diagnozy (
        id_diagnozy
    ASC );

ALTER TABLE diagnozy ADD CONSTRAINT diagnozy_pk PRIMARY KEY ( id_diagnozy );

CREATE TABLE gabinet (
    id_gabinetu    NUMBER(6) NOT NULL,
    numer_gabinetu VARCHAR2(10 BYTE)
);

CREATE UNIQUE INDEX gabinet_pk ON
    gabinet (
        id_gabinetu
    ASC );

ALTER TABLE gabinet ADD CONSTRAINT gabinet_pk PRIMARY KEY ( id_gabinetu );

CREATE TABLE gmina (
    id_gmina  NUMBER(6) NOT NULL,
    nazwa     VARCHAR2(50 BYTE),
    id_powiat NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX gmina_pk ON
    gmina (
        id_gmina
    ASC );

ALTER TABLE gmina ADD CONSTRAINT gmina_pk PRIMARY KEY ( id_gmina );

CREATE TABLE lekarze (
    id_lekarza       NUMBER(6) NOT NULL,
    imie             VARCHAR2(50 BYTE),
    nazwisko         VARCHAR2(50 BYTE),
    nr_licencji      NUMBER(7),
    id_specjalizacji NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX lekarze_nr_licencji_un ON
    lekarze (
        nr_licencji
    ASC );

CREATE UNIQUE INDEX lekarze_pk ON
    lekarze (
        id_lekarza
    ASC );

ALTER TABLE lekarze ADD CONSTRAINT lekarze_pk PRIMARY KEY ( id_lekarza );

ALTER TABLE lekarze ADD CONSTRAINT lekarze_nr_licencji_un UNIQUE ( nr_licencji );

CREATE TABLE lekarze_przychodnie (
    id_lekarza    NUMBER(6) NOT NULL,
    id_przychodni NUMBER(6) NOT NULL
);

CREATE INDEX lekarze_przychodnie_pk ON
    lekarze_przychodnie (
        id_przychodni
    ASC,
        id_lekarza
    ASC );

ALTER TABLE lekarze_przychodnie ADD CONSTRAINT lekarze_przychodnie_pk PRIMARY KEY ( id_przychodni,
                                                                                         id_lekarza );

CREATE TABLE leki (
    id_leku    NUMBER(6) NOT NULL,
    nazwa      VARCHAR2(100 BYTE),
    dawkowanie VARCHAR2(100 BYTE),
    opis       CLOB
);

CREATE UNIQUE INDEX leki_pk ON
    leki (
        id_leku
    ASC );

ALTER TABLE leki ADD CONSTRAINT leki_pk PRIMARY KEY ( id_leku );

CREATE TABLE miejscowosc (
    id_miejscowosc NUMBER(6) NOT NULL,
    nazwa          VARCHAR2(50 BYTE) NOT NULL,
    id_gmina       NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX miejscowosc_pk ON
    miejscowosc (
        id_miejscowosc
    ASC );

ALTER TABLE miejscowosc ADD CONSTRAINT miejscowosc_pk PRIMARY KEY ( id_miejscowosc );

CREATE TABLE pacjenci (
    id_pacjenta    NUMBER(6) NOT NULL,
    imie           VARCHAR2(50 BYTE),
    nazwisko       VARCHAR2(50 BYTE),
    pesel          VARCHAR2(11 BYTE),
    data_urodzenia DATE,
    telefon        VARCHAR2(9),
    email          VARCHAR2(100 BYTE),
    id_miejscowosc NUMBER(6) NOT NULL
);

ALTER TABLE pacjenci ADD CHECK ( length(imie) > 1 );

ALTER TABLE pacjenci ADD CHECK ( length(nazwisko) > 1 );

ALTER TABLE pacjenci ADD CHECK ( REGEXP_LIKE ( pesel,
                                                    '^[0-9]{11}$' ) );

ALTER TABLE pacjenci ADD CHECK ( REGEXP_LIKE ( telefon,
                                                    '^[0-9]{9}$' ) );

CREATE UNIQUE INDEX pacjenci_pesel_un ON
    pacjenci (
        pesel
    ASC );

CREATE UNIQUE INDEX pacjenci_pk ON
    pacjenci (
        id_pacjenta
    ASC );

ALTER TABLE pacjenci ADD CONSTRAINT pacjenci_pk PRIMARY KEY ( id_pacjenta );

ALTER TABLE pacjenci ADD CONSTRAINT pacjenci_pesel_un UNIQUE ( pesel );

CREATE TABLE powiat (
    id_powiat      NUMBER(6) NOT NULL,
    nazwa          VARCHAR2(50 BYTE),
    id_wojewodztwo NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX powiat_pk ON
    powiat (
        id_powiat
    ASC );

ALTER TABLE powiat ADD CONSTRAINT powiat_pk PRIMARY KEY ( id_powiat );

CREATE TABLE przychodnie (
    id_przychodni              NUMBER(6) NOT NULL,
    nazwa                      VARCHAR2(100 BYTE),
    adres                      VARCHAR2(40 BYTE),
    telefon                    NUMBER(9),
    id_miejscowosc NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX przychodnie_pk ON
    przychodnie (
        id_przychodni
    ASC );

ALTER TABLE przychodnie ADD CONSTRAINT przychodnie_pk PRIMARY KEY ( id_przychodni );

CREATE TABLE recepty (
    id_recepty       NUMBER(6) NOT NULL,
    data_wystawienia DATE,
    zalecenia        CLOB,
    id_leku          NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX recepty_pk ON
    recepty (
        id_recepty
    ASC );

ALTER TABLE recepty ADD CONSTRAINT recepty_pk PRIMARY KEY ( id_recepty );

CREATE TABLE specjalizacje (
    id_specjalizacji    NUMBER(6) NOT NULL,
    nazwa_specjalizacji VARCHAR2(100 BYTE),
    opis                CLOB
);

CREATE UNIQUE INDEX specjalizacje_pk ON
    specjalizacje (
        id_specjalizacji
    ASC );

ALTER TABLE specjalizacje ADD CONSTRAINT specjalizacje_pk PRIMARY KEY ( id_specjalizacji );

CREATE TABLE wizyty (
    id_wizyty      NUMBER(6) NOT NULL,
    id_pacjenta    NUMBER(6) NOT NULL,
    id_gabinetu    NUMBER(6) NOT NULL,
    data_wizyty    DATE,
    status         VARCHAR2(20 BYTE),
    id_recepty     NUMBER(6) NOT NULL,
    id_przychodni  NUMBER(6) NOT NULL,
    id_lekarza     NUMBER(6) NOT NULL,
    id_diagnozy    NUMBER(6) NOT NULL,
    id_badania     NUMBER(6) NOT NULL
);

CREATE UNIQUE INDEX wizyty_pk ON
    wizyty (
        id_wizyty
    ASC );

ALTER TABLE wizyty ADD CONSTRAINT wizyty_pk PRIMARY KEY ( id_wizyty );

CREATE TABLE wojewodztwo (
    id_wojewodztwo NUMBER(6) NOT NULL,
    nazwa          VARCHAR2(50 BYTE)
);

CREATE UNIQUE INDEX wojewodztwo_pk ON
    wojewodztwo (
        id_wojewodztwo
    ASC );

ALTER TABLE wojewodztwo ADD CONSTRAINT wojewodztwo_pk PRIMARY KEY ( id_wojewodztwo );

ALTER TABLE gmina
    ADD CONSTRAINT gmina_powiat_fk
        FOREIGN KEY ( id_powiat )
            REFERENCES powiat ( id_powiat );

ALTER TABLE lekarze
    ADD CONSTRAINT lekarze_specjalizacje_fk
        FOREIGN KEY ( id_specjalizacji )
            REFERENCES specjalizacje ( id_specjalizacji );

ALTER TABLE lekarze_przychodnie
    ADD CONSTRAINT lp_lekarze_fk
        FOREIGN KEY ( id_lekarza )
            REFERENCES lekarze ( id_lekarza );

ALTER TABLE lekarze_przychodnie
    ADD CONSTRAINT lp_przychodnie_fk
        FOREIGN KEY ( id_przychodni )
            REFERENCES przychodnie ( id_przychodni );

ALTER TABLE miejscowosc
    ADD CONSTRAINT miejscowosc_gmina_fk
        FOREIGN KEY ( id_gmina )
            REFERENCES gmina ( id_gmina );

ALTER TABLE pacjenci
    ADD CONSTRAINT pacjenci_miejscowosc_fk
        FOREIGN KEY ( id_miejscowosc )
            REFERENCES miejscowosc ( id_miejscowosc );

ALTER TABLE powiat
    ADD CONSTRAINT powiat_wojewodztwo_fk
        FOREIGN KEY ( id_wojewodztwo )
            REFERENCES wojewodztwo ( id_wojewodztwo );

ALTER TABLE przychodnie
    ADD CONSTRAINT przychodnie_miejscowosc_fk
        FOREIGN KEY ( id_miejscowosc )
            REFERENCES miejscowosc ( id_miejscowosc );

ALTER TABLE recepty
    ADD CONSTRAINT recepty_leki_fk
        FOREIGN KEY ( id_leku )
            REFERENCES leki ( id_leku );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_badania_fk
        FOREIGN KEY ( id_badania )
            REFERENCES badania ( id_badania );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_diagnozy_fk
        FOREIGN KEY ( id_diagnozy )
            REFERENCES diagnozy ( id_diagnozy );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_gabinet_fk
        FOREIGN KEY ( id_gabinetu )
            REFERENCES gabinet ( id_gabinetu );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_lp_fk
        FOREIGN KEY ( id_przychodni,
                      id_lekarza )
            REFERENCES lekarze_przychodnie ( id_przychodni,
                                                  id_lekarza );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_pacjenci_fk
        FOREIGN KEY ( id_pacjenta )
            REFERENCES pacjenci ( id_pacjenta );

ALTER TABLE wizyty
    ADD CONSTRAINT wizyty_recepty_fk
        FOREIGN KEY ( id_recepty )
            REFERENCES recepty ( id_recepty );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                            17
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

EXIT;