LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/gmina.csv'
BADFILE 'CTL/BAD/gmina.bad'
DISCARDFILE 'CTL/BAD/gmina.dsc'
INTO TABLE gmina
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_gmina,
  nazwa
)
