LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/rok.csv'
BADFILE 'CTL/BAD/rok.bad'
DISCARDFILE 'CTL/BAD/rok.dsc'
INTO TABLE rok
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_rok,
  rok
)
