LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/badania.csv'
BADFILE 'CTL/BAD/badania.bad'
DISCARDFILE 'CTL/BAD/badania.dsc'
INTO TABLE badania
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_badania,
  nazwa,
  opis
)
