LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/dzien.csv'
BADFILE 'CTL/BAD/dzien.bad'
DISCARDFILE 'CTL/BAD/dzien.dsc'
INTO TABLE dzien
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_dzien,
  dzien
)
