LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/miesiac.csv'
BADFILE 'CTL/BAD/miesiac.bad'
DISCARDFILE 'CTL/BAD/miesiac.dsc'
INTO TABLE miesiac
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_miesiac,
  miesiac
)
