LOAD DATA
CHARACTERSET AL32UTF8
INFILE 'CSV/status.csv'
BADFILE 'CTL/BAD/status.bad'
DISCARDFILE 'CTL/BAD/status.dsc'
INTO TABLE status
APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id_status,
  status
)
